- name: Install docker 
  hosts: setup-server
  become: true
  tasks:
    - name: Update
      apt:
        force_apt_get: yes
        update_cache: yes
    - name: Install prerequisite packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: Add Docker Offical GPG key
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        update_cache: true
    - name: Install the latest version of Docker Engine - Community
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      notify:
        - Start docker
  handlers:
    - name: Start docker
      service:
        name: docker
        state: started
