---
- name: Enable amazon-linux-extras docker
  shell: "amazon-linux-extras enable docker"

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no

- name: Install the latest version of docker
  package:
    name: 
      - docker
    state: latest

- name: Start docker
  service: 
    name: docker
    state: started
  become: yes

- name: user to the docker group
  user:
    name: "{{ ansible_user }}"
    shell: /bin/bash
    groups: docker
    append: yes
