
- name: Install Mosquitto 
  hosts: setup-server
  become: true
  vars:
    mosquitto_user: broker-user
    mosquitto_password: broker-password
    local_config_path: ../../templates/mosquitto/default.conf
    conf_path: /etc/mosquitto/conf.d/default.conf
  tasks:
    - name: Update
      apt:
        force_apt_get: yes
        update_cache: yes
    - name: Install Mosquitto
      package:
        name: mosquitto
        state: present
    - name: Ensure passwd is existed!
      file:
        path: /etc/mosquitto/passwd
        state: touch
    - name: Create password
      shell:
        cmd: "mosquitto_passwd -b /etc/mosquitto/passwd {{ mosquitto_user }} {{ mosquitto_password }}"
    - name: Copy env to remote server
      template:
        src: "{{ local_config_path }}"
        dest: "{{ conf_path }}"
      notify:
        - Restart Mosquitto
  handlers:
    - name: Restart Mosquitto
      service:
        name: mosquitto
        enabled: yes
        state: restarted
    