- name: Install s3fs and mount
  hosts: setup-server
  become: true
  vars:
    local_credential_path: ../../templates/s3fs/passwd-s3fs
    mount_point: /mnt/remote
    access_key: AKIAIOSFODNN7EXAMPLE
    secret_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    bucket_name: amzing
  tasks:
    - name: Update apt
      apt:
        update_cache: yes
    - name: Install s3fs
      package:
        name: s3fs
        state: latest
    - name: create mount point
      file:
        path: "{{ mount_point }}"
        state: directory
    - name: create s3 credential
      template:
        src: "{{ local_credential_path }}"
        dest: "/etc/passwd-s3fs"
        mode: 0600
    - name:
      mount:
        path: "{{ mount_point }}"
        src: "{{ bucket_name }}"
        fstype: fuse.s3fs
        opts: allow_other,use_path_request_style,url=http://localhost:9000                #--------->this opts for minio
        # opts: allow_other
        state: mounted