---
- name: Install prerequire
  apt:
    name:
      - git
      - unzip
      - software-properties-common
    state: present
  become: true

- name: Add php 7.4 apt repository 
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: true

- name: Install php
  apt:
    name:
      - php7.4
      - php7.4-common
      - php7.4-fpm
      - php7.4-mysql
      - php7.4-xml
      - php7.4-xmlrpc
      - php7.4-curl
      - php7.4-gd
      - php7.4-imagick
      - php7.4-cli
      - php7.4-dev
      - php7.4-imap
      - php7.4-mbstring
      - php7.4-opcache
      - php7.4-soap
      - php7.4-zip
      - php7.4-intl
    state: present
  become: yes
- name: Config php fpm user
  lineinfile:
    dest: /etc/php/7.4/fpm/pool.d/www.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^user =', line: 'user = {{ nginx_user }}' }
    - { regexp: '^group =', line: 'group = {{ nginx_user }}' }
    - { regexp: '^listen.owner =', line: 'listen.owner = {{ nginx_user }}' }
    - { regexp: '^listen.group =', line: 'listen.group = {{ nginx_user }}' }

- name: Config php.ini
  lineinfile:
    dest: /etc/php/7.4/fpm/php.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^upload_max_filesize', line: 'upload_max_filesize = 32M' }
    - { regexp: '^post_max_size', line: 'post_max_size = 48M' }
    - { regexp: '^memory_limit', line: 'memory_limit = 256M' }
    - { regexp: '^max_execution_time', line: 'max_execution_time = 600' }
    - { regexp: '^max_input_vars', line: 'max_input_vars = 3000' }
    - { regexp: '^max_input_time', line: 'max_input_time = 1000' }
  notify:
    - restart php-fpm