- name: Install Fail2ban 
  hosts: setup-server
  become: true
  tasks:
    - name: Update
      apt:
        force_apt_get: yes
        update_cache: yes
    - name: Install Fail2ban
      package:
        name: fail2ban
        state: present